CREATE WAREHOUSE IF NOT EXISTS SUBSTRACK_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for SubsTrack pipeline';

CREATE DATABASE IF NOT EXISTS SUBSTRACK_DB;

CREATE SCHEMA IF NOT EXISTS SUBSTRACK_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SUBSTRACK_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS SUBSTRACK_DB.SNAPSHOTS;
CREATE SCHEMA IF NOT EXISTS SUBSTRACK_DB.MARTS;

CREATE STAGE IF NOT EXISTS SUBSTRACK_DB.RAW.RAW_STAGE
  COMMENT = 'Landing zone for CSV files from Python CDC script';

CREATE FILE FORMAT IF NOT EXISTS SUBSTRACK_DB.RAW.CSV_FORMAT
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;
