CREATE STREAM IF NOT EXISTS SUBSTRACK_DB.RAW.CUSTOMERS_STREAM
  ON TABLE SUBSTRACK_DB.RAW.CUSTOMERS
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new records landed by Snowpipe';

CREATE STREAM IF NOT EXISTS SUBSTRACK_DB.RAW.PURCHASES_STREAM
  ON TABLE SUBSTRACK_DB.RAW.PURCHASES
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new purchase records landed by Snowpipe';
